# Generated by Django 3.0.4 on 2020-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgou_order',
            name='orders',
            field=models.ManyToManyField(to='TGous.Tgshoppings'),
        ),
    ]
