# Generated by Django 3.0.4 on 2020-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgou_order',
            old_name='shipping_address',
            new_name='shopping_address',
        ),
        migrations.AddField(
            model_name='tgou_order',
            name='shopping_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
