# Generated by Django 3.0.4 on 2020-04-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0002_tgshoppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgshoppings',
            old_name='shapping_name',
            new_name='shopping_name',
        ),
        migrations.RenameField(
            model_name='tgshoppings',
            old_name='shopping_monney',
            new_name='shopping_price',
        ),
    ]
