# Generated by Django 3.0.4 on 2020-04-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0002_tgou_order_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgou_order',
            old_name='tgou_Order',
            new_name='user',
        ),
    ]
