# Generated by Django 3.0.4 on 2020-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0002_auto_20200409_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgou_order',
            name='order_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
