# Generated by Django 3.0.4 on 2020-04-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0003_auto_20200409_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgou_order',
            old_name='ordedr_number',
            new_name='order_number',
        ),
    ]
