# Generated by Django 3.0.4 on 2020-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGous', '0003_auto_20200407_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgshoppings',
            name='shopping_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
