# Generated by Django 3.0.4 on 2020-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allorders',
            name='order_type',
        ),
    ]
