# Generated by Django 3.0.4 on 2020-04-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.CharField(max_length=200)),
                ('Quantity_of_Goods', models.CharField(max_length=10)),
                ('order_money', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=15)),
                ('order_data', models.DateField(auto_now=True)),
                ('order_state', models.CharField(max_length=10)),
                ('shipping_address', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
