# Generated by Django 3.0.4 on 2020-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200402_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_addre',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
