# Generated by Django 3.0.4 on 2020-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_remove_allorders_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorders',
            name='order_number',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
