# Generated by Django 3.0.4 on 2020-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_user_shopping_addre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopping_addre',
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
